const List<String> frasesMotivacionales = [
"Cada día es una nueva oportunidad para crecer.",
"El éxito no es para los que nunca fallan, sino para los que nunca se rinden.",
"Cree en ti mismo y todo será posible.",
"No esperes por el momento perfecto, haz que cada momento cuente.",
"La disciplina vence a la motivación cuando esta desaparece.",
"Cada paso, por pequeño que sea, te acerca a tu meta.",
"Aprende de los errores, pero nunca te quedes en ellos.",
"El único límite es el que tú te pones.",
"Persiste, incluso cuando nadie más crea en ti.",
"Hoy es un buen día para empezar algo grande.",
"Tu actitud determina tu dirección.",
"El miedo es solo una señal de que estás a punto de crecer.",
"No compares tu capítulo 1 con el capítulo 20 de alguien más.",
"Los grandes logros requieren tiempo y paciencia.",
"Convierte los obstáculos en oportunidades.",
"El esfuerzo de hoy es la victoria de mañana.",
"Rodéate de personas que eleven tu energía.",
"El cambio comienza desde adentro.",
"Sé constante, no perfecto.",
"No hay límites para quien cree en sí mismo.",
"Cada fracaso es una lección disfrazada.",
"Lo que haces hoy puede mejorar todos tus mañanas.",
"Mantén tu enfoque en lo que realmente importa.",
"El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
"Haz lo que amas y nunca trabajarás un día en tu vida.",
"La gratitud transforma lo que tenemos en suficiente.",
"Atrévete a soñar en grande.",
"La perseverancia es la clave que abre todas las puertas.",
"No te rindas antes de tiempo.",
"El cambio no es fácil, pero es posible.",
"Tu potencial es mucho mayor de lo que imaginas.",
"Cada momento es una oportunidad para reinventarte.",
"No busques la aprobación de los demás, encuentra la tuya propia.",
"Lo imposible solo tarda un poco más.",
"La acción es la diferencia entre soñar y lograr.",
"Sé valiente en lo que importa.",
"Tu esfuerzo constante vencerá a la suerte.",
"El éxito no llega, se construye.",
"Confía en el proceso.",
"Cada día es una página en blanco para escribir tu historia.",
"La paciencia y la persistencia vencen todo obstáculo.",
"No dejes que los errores definan tu futuro.",
"Tú eres el arquitecto de tu destino.",
"Aprende a disfrutar del camino, no solo del destino.",
"La acción supera la intención.",
"La resiliencia es la fuerza que transforma caídas en saltos.",
"Nunca subestimes el poder de tu actitud.",
"Lo que hoy parece difícil, mañana será tu fortaleza.",
"Cambia tus pensamientos y cambiarás tu mundo.",
"Sé la mejor versión de ti mismo cada día.",
"Las metas grandes requieren esfuerzo constante.",
"Confía en tu capacidad de superar cualquier desafío.",
"Nunca es tarde para comenzar de nuevo.",
"Tus sueños no tienen fecha de caducidad.",
"La motivación te inicia, la disciplina te mantiene.",
"Rodéate de energía positiva.",
"El éxito se construye con constancia y determinación.",
"El progreso es más importante que la perfección.",
"Cada reto es una oportunidad para crecer.",
"No dejes que los fracasos te detengan.",
"Cree en ti cuando nadie más lo haga.",
"La confianza en ti mismo es tu mejor arma.",
"Hoy es un buen día para cambiar tu vida.",
"El esfuerzo de hoy será la recompensa de mañana.",
"Haz cada día algo que te acerque a tu meta.",
"Las pequeñas victorias construyen grandes éxitos.",
"No busques atajos, construye tu camino.",
"El optimismo abre puertas que la duda cierra.",
"Cada día es una nueva oportunidad para triunfar.",
"Sé constante y verás los resultados.",
"Los sueños grandes comienzan con pasos pequeños.",
"La disciplina crea libertad.",
"No te compares, evoluciona.",
"El éxito se mide en esfuerzo, no en suerte.",
"Aprende algo nuevo cada día.",
"Sé dueño de tus decisiones.",
"No tengas miedo de empezar de nuevo.",
"El cambio requiere acción.",
"Cada día es un regalo, aprovéchalo.",
"Cree en tu capacidad de hacer la diferencia.",
"La persistencia convierte lo imposible en posible.",
"No esperes que las cosas sucedan, haz que sucedan.",
"El camino al éxito comienza con un paso.",
"La paciencia es la clave de los grandes logros.",
"Aprende a levantarte cada vez que caigas.",
"La confianza en ti mismo es la base de todo éxito.",
"El fracaso es solo un escalón hacia el éxito.",
"No te detengas hasta sentirte orgulloso.",
"Cada día cuenta, no lo desperdicies.",
"Sé el cambio que quieres ver en tu vida.",
"La determinación vence a la adversidad.",
"Haz lo mejor que puedas con lo que tengas.",
"Nunca dejes de aprender y crecer.",
"El esfuerzo constante supera al talento sin disciplina.",
"Cada desafío es una oportunidad de superación.",
"El éxito se construye con decisiones diarias.",
"Mantén la fe en ti mismo.",
"Cada día es una nueva oportunidad para mejorar.",
"La constancia es la clave del progreso.",
"No te rindas antes de tiempo, persiste.",
"El éxito es para los que actúan, no solo los que sueñan.",
"Confía en tu intuición.",
"El camino difícil lleva a lugares increíbles.",
"Sé fuerte, incluso cuando todo parezca difícil.",
"Lo que haces hoy marca tu mañana.",
"Cada paso hacia adelante es un paso hacia el éxito.",
"No importa lo lento que vayas, sigue avanzando.",
"Cree en la magia de los nuevos comienzos.",
"Nunca subestimes el poder de la perseverancia.",
"Aprende a superar tus límites.",
"El éxito comienza con un solo paso.",
"Rodéate de personas que inspiren tu grandeza.",
"Cada esfuerzo cuenta, no lo minimices.",
"La confianza y la acción crean resultados.",
"El cambio comienza con la decisión de intentarlo.",
"No te compares, cada camino es único.",
"La determinación hoy es la victoria mañana.",
"El fracaso no es el fin, es parte del proceso.",
"Sé persistente, los resultados llegarán.",
"Tu actitud define tu éxito.",
"Cada día es una oportunidad para aprender algo nuevo.",
"La constancia vence al talento cuando este no se esfuerza.",
"Nunca dejes de creer en ti.",
"Cada reto es una oportunidad disfrazada.",
"El éxito se mide por la superación personal, no por los demás.",
"Sé valiente y actúa a pesar del miedo.",
"Los pequeños pasos diarios generan grandes resultados.",
"Cree en ti, incluso cuando otros duden.",
"Cada día es una nueva oportunidad para ser mejor.",
"La disciplina es la herramienta del éxito.",
"No esperes a que las oportunidades lleguen, créalas.",
"Aprende a levantarte cada vez que caigas.",
"El esfuerzo diario produce resultados extraordinarios.",
"Sé constante en lo que importa.",
"Cada día es una página en blanco para escribir tu historia.",
"La perseverancia transforma los sueños en realidad.",
"No tengas miedo de fracasar, teme no intentarlo.",
"El éxito se construye paso a paso, día a día.",

"El secreto para avanzar es comenzar. — Mark Twain",
"El punto de partida de todo logro es el deseo. — Napoleon Hill",
"Los ganadores nunca se rinden, y los que se rinden nunca ganan. — Vince Lombardi",
"Cuando el camino se pone difícil, los fuertes se ponen en marcha. — Joe Kennedy",
"La mejor manera de predecir el futuro es crearlo. — Abraham Lincoln",
"Siempre haz un esfuerzo total, incluso cuando las probabilidades estén en tu contra. — Arnold Palmer",
"Cuanto más dura es la batalla, más dulce es la victoria. — Les Brown",
"No tengas miedo de renunciar a lo bueno para ir por lo grandioso. — John D. Rockefeller",
"No dejes que el miedo a perder sea mayor que la emoción de ganar. — Robert Kiyosaki",
"La pregunta no es quién me dejará; es quién me detendrá. — Ayn Rand",
"Es mejor fallar en originalidad que tener éxito en la imitación. — Herman Melville",
"No pienses, solo haz. — Horace",
"Comienza donde estás. Usa lo que tienes. Haz lo que puedas. — Arthur Ashe",
"Tus circunstancias presentes no determinan a dónde puedes ir; solo determinan desde dónde comienzas. — Nido Qubein",
"Debes esperar grandes cosas de ti mismo antes de poder lograrlas. — Michael Jordan",
"Haz lo que tengas que hacer hasta que puedas hacer lo que quieras hacer. — Oprah Winfrey",
"Nunca podrás cruzar el océano hasta que tengas el coraje de perder de vista la orilla. — Cristóbal Colón",
"Una forma de mantener el impulso es tener metas constantemente mayores. — Michael Korda",
"No necesitas ver toda la escalera, solo da el primer paso. — Martin Luther King Jr.",
"Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito. — Aristóteles",
"Dios siempre lucha junto a los que luchan. — Esquilo",
"Cambia tus pensamientos y cambiarás tu mundo. — Norman Vincent Peale",
"Es difícil vencer a una persona que nunca se rinde. — Babe Ruth",
"El entusiasmo mueve al mundo. — Arthur Balfour",
"La única persona con la que deberías intentar ser mejor, es la persona que eras ayer. — Matty Mullens",
"Nunca te rindas, porque ese es el lugar y momento justo donde la marea cambiará. — Harriet Beecher Stow",
"La diferencia entre un obstáculo y un escalón es qué tan alto levantas el pie. — Benny Lewis",
"Estudia mientras otros duermen; trabaja mientras otros holgazanean; prepárate mientras otros juegan; y sueña mientras otros solo desean. — William Arthur Ward",
"La diferencia entre lo imposible y lo posible radica en la determinación de una persona. — Tommy Lasorda",
"Más poderoso que la voluntad de ganar es el coraje de comenzar. — Orrin Woodward",
"No dejes que tus problemas te empujen; deja que tus sueños te guíen. — Ralph Waldo Emerson",
"No te ahogas por caer al agua; te ahogas por quedarte ahí. — Robert Collier",
"Si estás atravesando el infierno, sigue adelante. — Winston Churchill",
"Es mejor hacer algo imperfectamente que no hacer nada perfectamente. — Robert Schuller",
"Cree que puedes, y ya estarás a mitad de camino. — Teddy Roosevelt",
"Nuestra mayor debilidad está en rendirnos. La manera más segura de tener éxito es intentarlo solo una vez más. — Thomas Edison",
"La fortuna favorece al audaz. — Virgilio",
"Si quieres algo que nunca has tenido, debes hacer algo que nunca hayas hecho. — Thomas Jefferson",
"Nadie puede volver atrás y comenzar un nuevo principio, pero cualquiera puede comenzar hoy y hacer un nuevo final. — Maria Robinson",
"Nada funcionará a menos que tú lo hagas. — Maya Angelou",
"Cuanto más quiero lograr algo, menos lo llamo trabajo. — Richard Bach",
"El trabajo que haces mientras procrastinas probablemente sea el trabajo que deberías estar haciendo por el resto de tu vida. — Jessica Hische",
"Concéntrate en ser productivo en lugar de estar ocupado. — Tim Ferriss",
"El comienzo es la parte más importante del trabajo. — Platón",
"La motivación de un empleado es el resultado directo de la suma de interacciones con su gerente. — Bob Nelson",
"Se pierde más por indecisión que por la decisión equivocada. — Cicerón",
"Si no valoras tu tiempo, nadie más lo hará. — Kim Garst",
"Las cosas funcionan mejor para quienes hacen lo mejor con cómo funcionan las cosas. — John Wooden",
"Habrá obstáculos. Habrá dudas. Habrá errores. Pero con trabajo duro, no hay límites. — Michael Phelps",
"Construye tus propios sueños, o alguien más te contratará para construir los suyos. — Farrah Gray",
"Si trabajas en algo que realmente te importa, no necesitas que te empujen. La visión te atrae. — Steve Jobs",
"Para tener éxito debes aceptar todos los desafíos que se te presenten. No puedes aceptar solo los que te gustan. — Mike Gafka",
"Si quieres alcanzar la excelencia, puedes hacerlo hoy. A partir de este segundo, deja de hacer un trabajo menor. — Thomas J. Watson",
"El único lugar donde el éxito viene antes que el trabajo es en el diccionario. — Vidal Sassoon",
"Apuntamos por encima de la marca para dar en la marca. — Ralph Waldo Emerson",
"Las personas exitosas y no exitosas no varían mucho en sus habilidades. Varían en sus deseos de alcanzar su potencial. — John C. Maxwell",
"Cuando alguien me dice 'no', no significa que no puedo hacerlo, simplemente significa que no puedo hacerlo con ellos. — Karen E. Quinones Miller",
"Esfuérzate no por ser un éxito, sino por ser valioso. — Albert Einstein",
"La ideación sin ejecución es ilusión. — Robin Sharma",
"El individuo que dice que no es posible debe apartarse del camino de quienes lo están haciendo. — Tricia Cunningham",
"Tienes que levantarte cada mañana con determinación si quieres acostarte satisfecho. — George Lorimer",
"Cuanto más trabajo, más suerte parece tener. — Thomas Jefferson",
"No esperes a que el hierro esté caliente; hazlo caliente golpeando. — William Butler Yeats",
"Concéntrate en el viaje, no en el destino. La alegría se encuentra no en terminar, sino en hacer. — Greg Anderson",
"El secreto de la alegría en el trabajo se encuentra en una palabra: excelencia. — Pearl S. Buck",
"Mucho del estrés que sentimos no proviene de tener demasiado que hacer, sino de no terminar lo que empezamos. — David Allen",
"No dejes que lo que no puedes hacer interfiera con lo que sí puedes hacer. — John Wooden",
"Lo sabio hace de inmediato lo que el tonto hace al final. — Balthasar Gracian",
"Saber y no actuar es no saber. — Johann Wolfgang von Goethe",
"El celo sin conocimiento es fuego sin luz. — Thomas Huxley",
"La perfección es aburrida. Mejorar es donde está la diversión. — Dragos Roua",
"Nuestro mayor miedo no debe ser al fracaso, sino al éxito en cosas que realmente no importan. — Francis Chan",
"Nunca ganarás si nunca comienzas. — Helen Rowland",
"La forma más común en que las personas renuncian a su poder es pensando que no tienen ninguno. — Alice Walker",
"No importa lo que mires, sino lo que veas. — Henry David Thoreau",
"En algún lugar, algo increíble está esperando ser conocido. — Carl Sagan",
"La experiencia es una maestra dura porque primero da la prueba y luego la lección. — Vernon Sanders Law",
"Mantén tus ojos en las estrellas y los pies en la tierra. — Theodore Roosevelt",
"He quedado impresionado con la urgencia de hacer. Saber no es suficiente; debemos aplicar. Estar dispuesto no es suficiente; debemos hacer. — Leonardo da Vinci",
"Hay dos tipos de personas en este mundo: las que quieren hacer las cosas y las que no quieren cometer errores. — John C. Maxwell",
"Si no estás dispuesto a arriesgar lo habitual, tendrás que conformarte con lo ordinario. — Jim Rohn",
"Vive desde tu imaginación, no desde tu historia. — Stephen Covey",
"Si las decisiones que tomas sobre dónde inviertes tu sudor, sangre y lágrimas no son consistentes con la persona que aspiras a ser, nunca te convertirás en esa persona. — Clayton M. Christensen",
"Una persona que nunca cometió un error nunca intentó nada nuevo. — Albert Einstein",
"Recuerda siempre que eres absolutamente único, al igual que todos los demás. — Margaret Mead",
"Paso a paso, la cosa está hecha. — Charles Atlas",
"Dentro de veinte años estarás más decepcionado por las cosas que no hiciste que por las que hiciste. — Mark Twain",
"La voluntad de tener éxito es importante, pero lo que es más importante es la voluntad de prepararse. — Bobby Knight",
"Los obstáculos no deben detenerte. Si chocas contra un muro, no des la vuelta y te rindas. — Michael Jordan",
"No podemos ayudar a todos, pero todos pueden ayudar a alguien. — Ronald Reagan",
"Hay dos tipos de personas que te dirán que no puedes marcar la diferencia en este mundo: los que tienen miedo de intentar y los que tienen miedo de que tengas éxito. — Ray Goforth",
"Nos convertimos en lo que pensamos la mayor parte del tiempo. — Earl Nightingale",
"Desarrolla el éxito a partir de los fracasos. El desánimo y el fracaso son dos de los peldaños más seguros hacia el éxito. — Dale Carnegie",
"Si sigues pensando como siempre, seguirás obteniendo lo que siempre obtuviste. — Kevin Trudeau",
"Si puedes imaginarlo, puedes lograrlo; si puedes soñarlo, puedes convertirte en ello. — William Arthur Ward",
"Durante nuestros momentos más oscuros debemos enfocarnos para ver la luz. — Aristóteles Onassis",
"Cuanto más difícil la victoria, mayor la felicidad de ganar. — Pelé",
"Las cosas buenas llegan a quienes esperan, pero mejores a quienes salen y las buscan. — Grant Cardone",
"Tu talento es el regalo de Dios para ti. Lo que hagas con él es tu regalo de vuelta a Dios. — Leo Buscaglia",
"La manera más efectiva de hacerlo es hacerlo. — Amelia Earhart",
"Las dificultades reales se pueden superar; solo las imaginarias son inconquistables. — Theodore N. Vail",
"Mides el tamaño de un logro por los obstáculos que tuviste que superar para alcanzarlo. — Booker T. Washington",
"La clave es rodearte solo de personas que te eleven, cuya presencia saque lo mejor de ti. — Epicteto",
"Nutre tu mente con grandes pensamientos. Creer en lo heroico hace héroes. — Benjamin Disraeli",
"No pierdas tiempo golpeando una pared esperando transformarla en puerta. — Coco Chanel",
"Trabaja como si alguien estuviera trabajando 24 horas al día para quitártelo. — Mark Cuban",
"No soy producto de mis circunstancias. Soy producto de mis decisiones. — Stephen Covey",
"Avanza. No te detengas, no te quedes en tu camino, sino lucha por la meta que se te ha marcado. — George Whitefield",
"No puedo cambiar la dirección del viento, pero puedo ajustar mis velas para siempre llegar a mi destino. — Jimmy Dean",
"Algunas personas quieren que suceda, otras desean que suceda, otras lo hacen. — Michael Jordan",
"No puedes poner un límite a nada. Cuanto más sueñas, más lejos llegas. — Michael Phelps",
"Todo lo que la mente del hombre puede concebir y creer, lo puede lograr. — Napoleon Hill",
"Preferiría morir de pasión que de aburrimiento. — Vincent van Gogh",
"Encuentra una victoria en cada derrota para mantener la esperanza y una derrota en cada victoria para mantener la humildad. — Orrin Woodward",
"La razón por la que la mayoría de las personas nunca alcanza sus metas es porque no las definen ni las consideran creíbles o alcanzables. — Denis Watiley",
"La tragedia en la vida no está en no alcanzar tu meta. Está en no tener ninguna meta que alcanzar. — Benjamin Mays",
"No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas. — Robert Louis Stevenson",
"No te preocupes por que el mundo se acabe hoy. Ya es mañana en Australia. — Charles Schulz",
"No rebajes tu sueño solo para ajustarlo a tu realidad. Eleva tu convicción para que coincida con tu destino. — Stuart Scott",
"Apunta a la luna. Si fallas, aún podrías dar en una estrella. — W. Clement Stone",

"El éxito no es definitivo; el fracaso no es fatal. Lo que realmente cuenta es tener valor para continuar. — Winston Churchill",
"Es mejor fallar en la originalidad que triunfar en la imitación. — Herman Melville",
"El camino hacia el éxito y el camino hacia el fracaso son prácticamente el mismo. — Colin R. Davis",
"El éxito suele llegar a quienes están demasiado ocupados para buscarlo. — Henry David Thoreau",
"Desarrolla el éxito a partir de los fracasos. El desaliento y el fracaso son los peldaños hacia el éxito. — Dale Carnegie",
"Nada en este mundo puede tomar el lugar de la persistencia. El talento no lo hará; nada es más común que los hombres sin éxito y con talento. El genio no lo hará; que los genios no son recompensados es casi proverbial. La educación tampoco: el mundo está lleno de negligentes educados. El lema 'Sigue adelante' ha resuelto y resolverá siempre los problemas de la raza humana. — Calvin Coolidge",
"Hay tres caminos hacia el éxito definitivo. El primero es ser amable. El segundo es ser amable. El tercero es ser amable. — Mister Rogers",
"El éxito es la paz interior que resulta directamente de la autosatisfacción de saber que has hecho el esfuerzo de convertirte en lo mejor que eras capaz de ser. — John Wooden",
"Nunca he soñado con el éxito. He trabajado por él. — Estée Lauder",
"El éxito es obtener lo que quieres; la felicidad es querer lo que obtienes. — W. P. Kinsella",
"El pesimista ve la dificultad en cada oportunidad. El optimista ve la oportunidad en cada dificultad. — Winston Churchill",
"No dejes que el ayer ocupe mucho espacio de tu hoy. — Will Rogers",
"Se aprende más de los fracasos que de los éxitos. No dejes que esto te detenga. El fracaso te hace más fuerte. — Anónimo",
"Si trabajas en algo que te gusta y te apasiona, no necesitas un empujón. Tu visión será tu impulso. — Steve Jobs",
"La experiencia es una maestra dura porque primero te hace el examen y luego te da la lección. — Vernon Sanders Law",
"Saber cuánto puedes llegar a saber es el primer paso para aprender a vivir. — Dorothy West",
"Fijarse metas es el secreto para un futuro grandioso. — Tony Robbins",
"Concentra todos tus pensamientos sobre el trabajo en una mano. Los rayos del sol no queman hasta que hacen foco. — Alexander Graham Bell",
"O corres durante el día o el día corre por ti. — Jim Rohn",
"Creo profundamente en la suerte: cuanto más duro trabajo, más suerte tengo. — Thomas Jefferson",
"Cuando nos esforzamos en ser mejores de lo que somos, todo a nuestro alrededor mejora también. — Paulo Coelho",
"La mayoría de la gente pierde la oportunidad porque esta va vestida con un mono y parece trabajo. — Thomas Edison",
"Fijarse metas es el primer paso para transformar lo invisible en visible. — Tony Robbins",
"Tu trabajo va a suponer gran parte de tu vida, y la única forma de estar plenamente satisfecho es creer que se trata de un gran trabajo. El único modo de hacer un gran trabajo es amar lo que haces. Si aún no lo has encontrado, sigue buscando. No te conformes. Como sucede con todos los asuntos del corazón, cuando lo hayas encontrado te darás cuenta. — Steve Jobs",
"Las mujeres desafían el statu quo porque nunca lo han experimentado. — Cindy Gallop",
"No nos quedamos sentadas esperando a otras personas. Simplemente, nos ponemos en marcha y lo hacemos. — Arlan Hamilton",
"Piensa como una reina. Una reina no tiene miedo de fallar. El fracaso no es más que otro peldaño hacia la grandeza. — Oprah Winfrey",
"Los actos más valientes que puede realizar una mujer son amarse a sí misma, ser una misma y brillar por encima de aquellos que nunca creyeron que lo lograría. — Anónimo",
"Dondequiera que veas a una mujer triunfadora, busca a los tres hombres que tratarán de interponerse en su camino. — Yulia Timoshenko",
"Algunas mujeres eligen seguir a los hombres y otras eligen seguir sus sueños. Si te preguntas qué dirección tomar, recuerda que tu carrera nunca se despertará un día y te dirá que ya no te ama. — Lady Gaga",
"Algo que las mujeres todavía deben aprender es que nadie te da el poder: tienes que tomarlo. — Roseanne Barr",
"Una mujer ingeniosa es un tesoro; una belleza ingeniosa es un poder. — George Meredith",
"Cuando una mujer se convierte en su mejor amiga, la vida es más fácil. — Diane Von Furstenberg",
"Si quieres que algo se diga, pídeselo a un hombre. Si quieres que algo se haga, pídeselo a una mujer. — Margaret Thatcher",
"Necesitamos mujeres en todos los niveles, incluidos los más altos, para cambiar la dinámica, reformular la conversación, asegurarnos de que las voces de las mujeres sean escuchadas y atendidas, no pasadas por alto e ignoradas. — Sheryl Sandberg",
"Me llevó bastante tiempo conseguir una voz y, ahora que la tengo, no pienso quedarme en silencio. — Madeleine Albright",
"Las mujeres deben aprender a jugar el juego como los hombres. — Eleanor Roosevelt",
"Juro por mi vida y por mi amor a ella, que jamás viviré para el provecho de otro hombre, ni le pediré a otro hombre que viva para el mío. — Ayn Rand",
"El que se conquista a sí mismo es el guerrero más poderoso. — Confucio",
"No trates de convertirte en un hombre de éxito, sino más bien en un hombre de valor. — Albert Einstein",
"Un hombre con coraje hace una mayoría. — Andrew Jackson",
"Uno de los secretos del éxito en la vida es estar preparados para cuando se presenta la oportunidad. — Benjamin Disraeli",
"El hombre que comete un error y no lo corrige, está cometiendo otro error. — Confucio",
"El hombre exitoso sacará provecho de sus errores y volverá a intentarlo de otro modo. — Dale Carnegie",
"Un hombre de éxito es aquel capaz de construir unos cimientos firmes con los ladrillos que otros le han arrojado. — David Brinkley",
"Es un hombre sabio aquel que no se entristece por las cosas que no tiene, sino que se regocija por las que tiene. — Epicteto",
"Debes levantarte cada mañana con determinación si quieres irte a la cama con satisfacción. — George Lorimer",
"La educación es el arma más poderosa para cambiar el mundo. — Nelson Mandela",
"Lo más difícil es la decisión de actuar: el resto es mera tenacidad. — Amelia Earhart",
"Descubrirás que la educación es prácticamente lo único que queda libre en este mundo, lo único de lo que el ser humano puede disponer tanto como esté dispuesto a llevarse. — John Graham",
"Adopta la actitud de un estudiante, nunca te consideres demasiado mayor para hacer preguntas ni demasiado listo como para aprender algo nuevo. — Augustine Og Mandino",

"Sé el cambio que quieres ver en el mundo. — Mahatma Gandhi",
"No se trata de si van a derribarte, se trata de si vas a levantarte cuando lo hagan. — Vince Lombardi",
"Nadie puede hacerte sentir inferior sin tu consentimiento. — Eleanor Roosevelt",
"Qué maravilloso es que nadie tenga que esperar ni un segundo para empezar a mejorar el mundo. — Ana Frank",
"El pesimista ve dificultades en cada oportunidad. El optimista ve oportunidades en cada dificultad. — Winston Churchill",
"Muchos piensan en cambiar el mundo, pero casi nadie piensa en cambiarse a sí mismo. — Leon Tolstoi",
"Si estás trabajando en algo que te importa de verdad, nadie tiene que empujarte: tu visión te empuja. — Steve Jobs",
"No tienes que ser grande para empezar. Pero tienes que empezar para poder ser grande. — Zig Ziglar",
"Podemos sufrir muchas derrotas pero no debemos ser derrotados. — Maya Angelou",
"El momento en que quieres dejarlo es justo el momento en que tienes que seguir avanzando. — Anónimo",
"No esperes. Nunca va a ser el momento adecuado. — Napoleon Hill",
"La creatividad es la inteligencia divirtiéndose. — Albert Einstein",
"Rodéate de personas que crean en tus sueños, animen tus ideas, apoyen tus ambiciones, y saquen lo mejor de ti. — Roy T. Bennet",
"No importa lo que te diga la gente, las palabras y las ideas pueden cambiar el mundo. — Robin Williams",
"Nunca eres demasiado viejo para marcarte otra meta o tener un nuevo sueño. — C.S. Lewis",
"No te pliegues. No lo diluyas. No intentes hacerlo lógico. No adaptes tu propia alma a las costumbres de los demás. En lugar de eso, sigue tu propia obsesión implacablemente. — Franz Kafka",
"La mayor parte de las grandes cosas que ha conseguido el hombre, fueron declaradas imposibles antes de que alguien las hiciera. — Louis D. Brandeis",
"La verdadera motivación procede de trabajar en cosas que nos importan. — Sheryl Sandberg",
"La energía y la persistencia conquistan todas las cosas. — Benjamin Franklin",
"Sé amable, porque toda persona que conoces está librando una gran batalla. — Platón",
"La lógica te llevará de la A a la Z. La imaginación te llevará a cualquier lugar. — Albert Einstein",
"Las ideas no duran mucho. Hay que hacer algo con ellas. — Santiago Ramón y Cajal",
"Te deseo que estés vivo cada día de tu vida. — Jonathan Swift",
"La excelencia no es un acto, es un hábito. — Aristóteles",
"Sé tú mismo. Todos los demás ya están ocupados. — Oscar Wilde",
"No dejes que tu pasado ocupe todo tu presente. — Will Rogers",
"Lo que importa no es lo que te ocurre, sino cómo reaccionas a ello. — Epicteto",
"A veces no conoces el valor de un momento hasta que se ha convertido en un recuerdo. — Dr. Seuss",
"No es la muerte lo que debes temer, sino nunca empezar a vivir. — Marco Aurelio",
"El que pasa el tiempo arrepintiéndose del pasado, pierde el presente y arriesga el futuro. — Francisco de Quevedo",
"La vida es como montar en bicicleta. Para mantener el equilibrio tienes que avanzar. — Albert Einstein",
"La vida es en un 10% lo que te ocurre, y en un 90% cómo te lo tomas. — Charles R. Swindoll",
"Camina hacia el sol y las sombras quedarán siempre tras de ti. — Walt Whitman",
"No pares cuando estés cansado. Para cuando hayas terminado. — Marilyn Monroe",
"Qué locura o desatino me lleva a contar las faltas ajenas, teniendo tanto que decir de las mías. — Miguel de Cervantes",
"Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre. — Mahatma Gandhi",
"Solo yo puedo cambiar mi vida. Nadie puede hacerlo por mí. — Carol Burnett",
"Hemos sido llamados para curar heridas, para unir lo que se ha separado, y para traer a casa a quienes han perdido su camino. — San Francisco de Asís",
"El mayor peligro para la mayoría de nosotros no es apuntar demasiado alto y fallar, sino apuntar demasiado bajo y acertar. — Michelangelo Buonarroti",
"El que cree que lo sabe todo es incapaz de aprender. — Epicteto",
"La mala noticia es que el tiempo vuela. La buena noticia es que tú eres el piloto. — Michael Altshuler",
"Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud. — Maya Angelou",
"No es verdad que las personas paren de perseguir sueños porque se hacen viejos. Se hacen viejos porque dejan de perseguir sueños. — Gabriel García Márquez",
"La felicidad no ocurre por casualidad, sino por elección. — Jim Rohn",
"Hay dos grandes días en la vida de una persona: el día en que nacemos, y el día en que descubrimos para qué. — William Barclay",

"Demasiada gente no vive sus sueños porque está ocupada viviendo sus miedos. — Les Brown",
"Solo aquellos que se arriesgan a caer pueden conseguir grandes cosas. — Robert F. Kennedy",
"Generamos miedos cuando estamos sentados. Y los superamos con la acción. — Dr. Henry Link",
"No mires hacia atrás - no es allí adonde vas. — Emilio Valcárcel",
"Avanza con confianza en la dirección de tus sueños. — Thoreau",
"Saber qué es lo correcto y no hacerlo es falta de valor. — Confucio",
"Todo lo que siempre deseaste está al otro lado del miedo. — George Addair",
"La inacción produce duda y miedo. La acción genera confianza y valor. Si quieres dominar el miedo no te quedes en casa pensando sobre ello: sal fuera y enfréntate a él. — Dale Carnegie",
"Tienes que hacer las cosas que crees que no puedes hacer. — Eleanor Roosevelt",
"Tu vida se encoge o se expande en proporción a tu valor. — Anais Nin",
"Sal de tu zona de confort. Solo puedes crecer si estás dispuesto a sentirte raro e incómodo cuando intentas algo nuevo. — Brian Tracy",
"He aprendido que el valor no es la ausencia de miedo, sino el triunfo sobre él. El hombre valiente no es el que no siente miedo, sino el que lo domina. — Nelson Mandela",
"Es imposible vivir sin fracasar en algo, a no ser que vivas con tanto cuidado que dé igual si has vivido o no – en cuyo caso, ya has fracasado. — J.K. Rowling",
"El carácter no puede desarrollarse en la calma y en la facilidad. Solo a través de la experiencia y del sufrimiento se fortalece el alma, se inspira la ambición, y se alcanza el éxito. — Hellen Keller",
"Lo que cuenta no es de dónde vienes, sino adónde vas. — Ella Fitzgerald",
"Sólo se vive una vez. Pero si lo haces bien, una vez basta. — Mae West",
"Nunca, nunca, nunca abandones. — Winston Churchill",
"La fuerza no procede de la capacidad física, sino de una voluntad indomable. — Mahatma Gandhi",
"La diligencia es la madre de la buena suerte. — Benjamin Franklin",
"Cuando te levantes por la mañana piensa en qué privilegio es estar vivo, pensar, disfrutar, amar. — Marco Aurelio",
"Si hay algo en nosotros verdaderamente divino, es la voluntad. Por ella afirmamos la personalidad, templamos el carácter, desafiamos la adversidad, reconstruimos el cerebro y nos superamos diariamente. — Santiago Ramón y Cajal",
"Solo el que intenta lo absurdo es capaz de conseguir lo que parecía imposible. — Miguel de Unamuno",
"Concentra todos tus pensamientos en el trabajo que tienes entre manos. Los rayos del sol no encienden fuego hasta que los enfocas en un solo punto. — Alexander Graham Bell",
"Cuanto más grande es la dificultad, más gloria hay en superarla. — Epicuro",
"Si no puedes volar, corre; si no puedes correr, camina; si no puedes caminar, arrástrate, pero hagas lo que hagas sigue moviéndote hacia adelante. — Martin Luther King",
"La palabra 'no' solo significa que empieces otra vez en un nivel superior. — Peter Diamandis",
"No he llegado tan lejos solo para llegar hasta aquí. — Anónimo",
"Si no puedes dejar de pensar en ello, no dejes de trabajar en ello. — Anónimo",
"En la vida no se trata de encontrarte a ti mismo. Se trata de inventarte a ti mismo. — George Bernard Shaw",
"Tu tiempo es limitado, no lo malgastes viviendo la vida de otro. No te dejes atrapar por el dogma. — Steve Jobs",
"No preguntes cuál es tu lugar en el mundo: siéntate en él. — Emilio Valcárcel",
"El mayor logro es ser tú mismo en un mundo que continuamente trata de convertirte en otra cosa. — Ralph Waldo Emerson",
"Nunca soñé con el éxito. Trabajé por él. — Estée Lauder",
"Nunca es demasiado tarde para ser lo que podrías haber sido. — George Eliot",
"El éxito es mi única opción, no el fracaso. — Eminem",
"No es que tenga talento: estoy obsesionado. — Connor McGregor",
"No tienes poder sobre los acontecimientos exteriores - pero sí sobre tu mente. Aprende esto, y encontrarás tu fuerza. — Marco Aurelio",
"El hombre que se levanta es más grande que el que nunca ha caído. — Concepción Arenal",
"La mejor almohada para dormir es una conciencia tranquila. — Sócrates",
"El arte de vencer se aprende en las derrotas. — Simón Bolívar",
"Olvida siempre a tus enemigos: nada les molesta más. — Oscar Wilde",
"El conocimiento es poder. — Francis Bacon",
"La buena vida es una forma de pensar. — Emilio Valcárcel",
"Solo quien se maneja a sí mismo puede manejar a los demás. — José Ortega y Gasset",
"Ser positivo no significa que todo vaya a salir bien. Significa saber que vas a estar bien independientemente de cómo salgan las cosas. — Anónimo",
"Todos los hombres que no tienen nada importante que decir hablan a gritos. — Enrique Jardiel Poncela",
"Tenemos dos orejas y una boca para escuchar el doble de lo que hablamos. — Epicteto",
"Un campeón se distingue no por sus victorias, sino por cómo se recupera de sus derrotas. — Serena Williams",
"Aferrarse al rencor es como beber veneno y esperar que otra persona muera. — Buda",
"Una persona inteligente resuelve los problemas. Una persona sabia los evita. — Albert Einstein",
"A menudo las dificultades preparan a una persona normal para un destino extraordinario. — C.S. Lewis",
"Dentro de veinte años estarás más arrepentido por las cosas que no hiciste que por aquellas que hiciste. — Mark Twain",
"La perseverancia a pesar de todos los obstáculos, desánimos e imposibilidades: esto es lo que distingue el alma fuerte de la débil. — Thomas Carlyle",
"Trabajar duro por algo que no te importa se llama estrés. Trabajar duro por algo que te importa de verdad se llama pasión. — Simon Sinek",
"Recuerda que, a veces, no conseguir lo que quieres es un gran golpe de suerte. — Dalai Lama",
"Para tener éxito la actitud es tan importante como la habilidad. — Walter Scott",
"Hecho es mejor que perfecto. — Sheryl Sandberg",
"En ese lugar entre tu zona de confort y tu sueño es donde está la verdadera vida. — Helen Keller",
"Empieza haciendo lo que es necesario; después haz lo que es posible; y pronto te encontrarás haciendo lo imposible. — San Francisco de Asís",
"Las frases motivadoras pueden inspirarte; pero es la acción la que te completa. — Anónimo",
"Los obstáculos son esas cosas atemorizantes que ves cuando apartas los ojos de tu meta. — Henry Ford",
"Más que producto de mis circunstancias, soy producto de mis decisiones. — Stephen R. Covey",
"La cuestión no es quién va a permitírmelo, sino quién va a ser capaz de pararme. — Ayn Rand",
"La acción es la verdadera medida de la inteligencia. — Napoleon Hill",
"La perfección es imposible. Pero si aspiramos a ella podemos alcanzar la excelencia. — Vince Lombardi",
"Sé tan bueno que no puedan ignorarte. — Steve Martin",
"La Fortuna ayuda a los audaces. — Virgilio",

"Si todos avanzamos juntos, el éxito llegará solo. — Henry Ford",
"Seamos los líderes que hubiéramos deseado tener. — Simon Sinek",
"Nunca dudes de que un pequeño grupo de ciudadanos reflexivos y comprometidos puede cambiar el mundo; de hecho, es lo único que lo ha logrado. — Margaret Mead",
"Individualmente, somos una gota. Juntos, somos el mar. — Ryunosuke Satoro",
"Lo lindo del trabajo en equipo es que siempre tienes a alguien a tu lado. — Margaret Carty",
"Los buenos equipos no se guardan nada. No temen sacar los trapitos al sol. Admiten sus errores, sus debilidades y sus preocupaciones sin temor a las represalias. — Patrick Lencioni",
"Un hombre puede ser imprescindible para un equipo, pero ningún equipo está compuesto por un solo hombre. — Kareem Abdul-Jabbar",
"El compromiso individual con el esfuerzo colectivo es lo que hace que un equipo, una empresa, una sociedad y hasta una civilización funcionen. — Vince Lombardi",
"Nuestro amor es tan grande que hay lugar para todos. — Cari Tuna",
"Los buenos equipos incorporan el trabajo en grupo a la cultura, creando así los pilares del éxito. — Ted Sundquist",
"Lo que la gente puede elegir, también lo puede cambiar. — Madeleine Albright",
"Algunas personas quieren que algo suceda, otras sueñan con que suceda, pero hay otras que lo hacen realidad. — Michael Jordan",
"Los verdaderos héroes están hechos de integridad. — Hope Solo",
"Las cosas se consiguen trabajando duro. Es el trabajo lo que genera cambios. — Shonda Rhimes",
"Las marcas deben empoderar a sus comunidades para que sean agentes de cambio por derecho propio. — Simon Mainwaring",
"No ganaré siempre, pero sí seré fiel a mí mismo. No siempre tendré éxito, pero sí viviré según mis convicciones. — Abraham Lincoln",
"Promovamos la productividad real, no la imagen del trabajo duro. — Scott Belsky",
"Ten el coraje de seguir tu corazón e intuición. De algún modo, ya saben lo que realmente quieres ser. — Steve Jobs",
"La clave para un liderazgo exitoso hoy en día es tener influencia, no autoridad. — Ken Blanchard",
"El único límite para nuestros logros del mañana son las dudas que tenemos hoy. — Franklin D. Roosevelt",
"Cuando algo es lo suficientemente importante, hazlo igual aunque las probabilidades no estén a tu favor. — Elon Musk",
"La verdad reside en la simplicidad y no en la multiplicidad y la confusión de las cosas. — Sir Isaac Newton",
"La gente que trabaja bien se siente bien y la gente cuyo trabajo es excepcional se siente excepcional. — Mark Sanborn",
"El éxito es, en gran medida, una combinación de suerte y trabajo duro. — Dustin Moskovitz",
"Ten siempre la mente abierta y el corazón compasivo. — Phil Jackson",
"El mayor riesgo es no correr ningún riesgo. En un mundo que cambia rápidamente, la única estrategia que sin lugar a dudas fallará es la de no tomar riesgos. — Mark Zuckerberg",
"Un emprendedor es alguien que saltaría de un precipicio y armaría un aeroplano mientras cae. — Reid Hoffman",
"Las palabras amables pueden ser breves y fáciles de decir, pero sus ecos son realmente infinitos. — Madre Teresa",
"Sé brutalmente honesto con lo de corto plazo, y optimista y confiado con lo planteado a largo plazo. — Reed Hastings",
"Ser exitoso es una elección; por lo tanto, ser derrotado es una decisión. — Jim Stovall",
"No importa de dónde vienes. Solo importa hacia dónde vas. — Brian Tracy",
"La audacia es como un músculo. Sé por experiencia personal que mientras más la ejercito, más natural se vuelve no permitir que mis miedos me detengan. — Arianna Huffington",
"El único camino es seguir adelante. — Robert Frost",
"No te dejes intimidar por lo que no sabes. Puede ser tu mayor fortaleza y la clave para hacer las cosas de un modo diferente a los demás. — Sara Blakely",
"Uno no elige cómo perder, pero sí puede elegir cómo volver a intentarlo y prepararse para ganar la próxima vez. — Pat Riley",
"Cuando me atrevo a ser poderosa, a usar mis fortalezas al servicio de mi visión, el miedo se vuelve cada vez menos importante. — Audre Lorde",
"Quiero que las niñas crezcan sabiendo que pueden hacer lo que deseen, incluso jugar al fútbol. — Jen Welter",
"No importa cuántas metas hayas logrado, siempre debes poner la mirada en un objetivo más alto. — Jessica Savitch",
"El pensamiento positivo es una herramienta muy valiosa que puede, además, ayudarte a superar obstáculos y alcanzar objetivos nuevos. — Amy Morin",
"El último 10 % que se necesita para lograr algo, requiere tanta energía como el primer 90 %. — Rob Kalin",
"La unión hace la fuerza... cuando hay trabajo en equipo y colaboración, se pueden lograr grandes cosas. — Mattie Stepanek",
"La motivación surge de trabajar en lo que nos gusta. También, de trabajar con las personas que nos gustan. — Sheryl Sandberg",
"Todo comienza con una idea excelente y con trabajo en equipo. — Garrett Camp",
"Una empresa es tan buena como la gente que trabaja en ella. — Mary Kay Ash",
"Trabajar en equipo es la habilidad de trabajar juntos en pos de una visión en común. Es el combustible que hace que gente común logre resultados extraordinarios. — Andrew Carnegie",
"El arte de la escucha efectiva es esencial para que las comunicaciones sean claras, y las comunicaciones claras son imprescindibles para lograr el éxito. — James Cash Penney",
"Tanto en los grupos como en las relaciones no podemos triunfar solos. — Terry Orlick",
"El trabajo en equipo es el secreto para que la gente común logre resultados extraordinarios. — Ifeanyi Enoch Onuoha",
"Con un equipo entusiasta puedes lograr casi cualquier cosa que te propongas. — Tahir Shah",
"Trabaja con pasión y a gusto a cada minuto todos los días hasta que alcances tu objetivo. — Ava DuVernay",
"Nuestra mayor debilidad reside en darse por vencido. La forma más segura de alcanzar el éxito es siempre intentarlo una vez más. — Thomas Edison",
"Los grandes logros siempre se producen en un marco de grandes expectativas. — Charles F. Kettering",
"El éxito puede hacer que las personas desaprendan los hábitos que inicialmente las llevaron a ese mismo éxito. — Satya Nadella",
"Los sueños nunca se pierden. Solo se incuban en forma de hobbies. — Larry Page",
"El éxito no se logra, se atrae. — Farshad Asl",
"La buena gestión es como poder escalar una montaña hasta alcanzar la cima con éxito; lo que determina si el camino elegido para el ascenso es el correcto es el liderazgo. — Stephen Covey",
"El éxito se mide, no tanto por la posición que uno ha alcanzado en la vida sino por los obstáculos que ha superado. — Booker T. Washington",
"Los buenos líderes no tienen éxito por ser grandes personas; tienen éxito porque revelan la grandeza de los demás. — Jon Gordon",
"Lo que da felicidad es la elaboración de las cosas. Hay que disfrutar del proceso independientemente de que el resultado sea el éxito o el fracaso. — Caterina Fake",
"Hay dos tipos de personas que te dirán que no puedes marcar la diferencia en este mundo: las que temen intentarlo y las que temen que tú lo logres. — Ray Goforth",
"Puedes ser alguien que se destaca o alguien invisible. Tú eliges. — Seth Godin",
"La imaginación es más importante que el conocimiento. — Albert Einstein",
"Las imperfecciones no son defectos; son lo que nos recuerda que estamos todos en el mismo barco. — Brené Brown",
"Hay personas que ven a la innovación como un cambio, pero nosotros nunca lo hemos visto así. En realidad se trata de mejorar las cosas. — Tim Cook",
"Sé claro. Sé auténtico. Pon límites. Analiza tu visión. Haz lo que te importa a ti. Y conoce lo que vales. — Iyanla Vanzant",
"Siempre hay una oportunidad para marcar la diferencia. — Michael Dell",
"Nunca nada habrá terminado. Es un ejercicio continuo. — Dara Khosrowshahi",
"La fuerza más poderosa que tenemos para cambiar el mundo son las mujeres que elevan la voz por sí mismas y por quienes las rodean. — Melinda Gates",
"Pide ayuda a tus colegas, rápido y seguido. — Jill Konrath",
"La gente con objetivos tiene éxito porque sabe a dónde se dirige. — Earl Nightingale",

"Si no intentas nada, no puedes fracasar... para tener la vida que deseas hay que tener agallas. — Richard Yates",
"No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas. — Jack Canfield",
"El fracaso es un sentimiento que nace mucho antes de que se convierta en un resultado real. Es una vulnerabilidad que se engendra con la duda y luego se intensifica, a menudo de manera intencionada, por el miedo. — Michelle Obama",
"Todo fracaso es la falta de adaptación, todo éxito es una adaptación que ha resultado exitosa. — Max McKeown",
"Debes renunciar a lo que fuiste, para convertirte en quien deseas ser. — Janet Fitch",
"Rendirse es la única manera segura de fracasar. — Gena Showalter",
"Nunca dejes que el miedo se interponga en tu camino. — Babe Ruth",
"Cada uno de los fracasos tiene siempre un lado bueno si realmente quieres seguir en juego. — Barbara Corcoran",
"Cambia lo que se puede cambiar, acepta lo que no se puede modificar y aléjate de lo que no se puede aceptar. — Denis Waitley",
"No dejes que lo que no puedes hacer interfiera con lo que sí puedes. — John Wooden",
"No le temo a las tormentas, porque estoy aprendiendo a timonear mi barco. — Louisa May Alcott",
"Haz eso que crees que no puedes hacer. Falla. Vuelve a intentarlo. Hazlo mejor la segunda vez. Las únicas personas que no se derrumban nunca son las que nunca estuvieron en la cuerda floja. — Oprah Winfrey",
"Cualquiera puede darse por vencido, es lo más fácil de hacer del mundo. Pero mantenerse a flote cuando todos esperarían que te derrumbaras, eso es fortaleza de verdad. — Chris Bradford",
"Todo es posible si lo deseas con la suficiente convicción. — J.M. Barrie",
"Sé valiente. Toma riesgos. No hay nada que sustituya a la experiencia. — Paulo Coelho",
"Espera lo inesperado. Y, siempre que sea posible, sé lo inesperado. — Lynda Barry",
"No importa cuántas veces hayas fracasado. Solo tiene que salir bien una vez. — Mark Cuban",
"Entre poder y hacer hay un océano de diferencia y, muchas veces, en el fondo yacen los restos del naufragio con la falta de voluntad. — Marie von Ebner-Eschenbach",
"La manera más efectiva de hacer algo es haciéndolo. — Amelia Earhart",
"Si puedes bailar, ser libre y no sentir vergüenza, el mundo entero puede ser tuyo. — Amy Poehler",
"No tienes que ser excelente en algo para empezar, pero sí tienes que empezar para llegar a ser excelente en algo. — Zig Ziglar",
"Lo normal no es más que un ciclo en la lavadora. — Whoopi Goldberg",
"Es difícil no hacer nada... nunca sabes cuándo has terminado. — Leslie Nielsen",
"Sé como una estampilla de correo. Pégate a lo que quieras y no te salgas hasta que hayas llegado. — Josh Billings",
"Cambiar no es un insulto... pero tu reacción al cambio, a veces, puede parecer que lo fuera. — Jeffrey Gitomer",
"El camino al éxito está siempre en construcción. — Lily Tomlin",
"El ascensor hacia el éxito no funciona. Tendrás que subir las escaleras... un paso a la vez. — Joe Girard",

"No importa que vayas despacio, mientras no te detengas. — Confucio",
"No te rindas, por favor no cedas, aunque el frío queme, aunque el miedo muerda, aunque el sol se esconda y se calle el viento, aún hay fuego en tu alma, aún hay vida en tus sueños. — Mario Benedetti",
"No te dejes intimidar por las opiniones de los demás. Solo la mediocridad es segura, así que arriésgate y haz aquello que deseas. — Paulo Coelho",
"Nuestra mayor debilidad es rendirnos. La forma más segura de ganar es intentarlo una vez más. — Thomas Edison",
"Cambia la forma en que miras las cosas, y las cosas que miras cambiarán. — Wayne Dyer",
"Los días difíciles son necesarios para que disfrutemos con más entusiasmo de los días felices. — Roberto Shinyashiki",
"Todo lo que un sueño necesita para hacerse realidad es que alguien crea que puede hacerse realidad. — Roberto Shinyashiki",
"Errar es humano y echarle la culpa a la computadora, aun más. — Robert Orben",

"No importa que vayas despacio, mientras no te detengas. — Confucio",
"No te rindas, por favor no cedas, aunque el frío queme, aunque el miedo muerda, aunque el sol se esconda y se calle el viento, aún hay fuego en tu alma, aún hay vida en tus sueños. — Mario Benedetti",
"No te dejes intimidar por las opiniones de los demás. Solo la mediocridad es segura, así que arriésgate y haz aquello que deseas. — Paulo Coelho",
"Nuestra mayor debilidad es rendirnos. La forma más segura de ganar es intentarlo una vez más. — Thomas Edison",
"Cambia la forma en que miras las cosas, y las cosas que miras cambiarán. — Wayne Dyer",
"Los días difíciles son necesarios para que disfrutemos con más entusiasmo de los días felices. — Roberto Shinyashiki",
"Todo lo que un sueño necesita para hacerse realidad es que alguien crea que puede hacerse realidad. — Roberto Shinyashiki",
"Errar es humano y echarle la culpa a la computadora, aun más. — Robert Orben",
"Un día, cuando mires atrás, verás que los días más lindos fueron aquellos en los que luchaste. — Sigmund Freud",
"Un hombre creativo está motivado por el deseo de lograr, no por el deseo de vencer a los demás. — Ayn Rand",
"No contengas tu inspiración e imaginación; no te conviertas en el esclavo de tu modelo. — Vincent Van Gogh",
"La única revolución posible es dentro de uno mismo. — Octavio Paz",
"Vivir es abrigar sueños y esperanzas, haciendo de la fe nuestra mayor inspiración. ¡Es buscar en las pequeñas cosas un gran motivo para ser feliz! — Mario Quintana",
"La felicidad no es algo prefabricado. Está compuesta de tus propias acciones. — Dalai Lama",
"El optimismo es la fe que lleva al éxito; nada se puede hacer sin esperanza. — Helen Keller",
"No es la carga lo que te derrumba, sino la forma en que la llevas. — Lou Holtz",
"No hay nada completamente errado en el mundo, incluso un reloj parado puede estar en lo cierto dos veces al día. — Paulo Coelho",
"Una persona sabia es aquella que conoce los límites de su propia ignorancia. — Sócrates",
"Si no me veo a mí misma en lo que hago, si no veo mi lucha, no tiene sentido. — Gioconda Belli",
"Descubre quién eres y sé esa persona. Tu alma fue puesta en este mundo para ser eso, así que vive esa verdad y todo lo demás vendrá. — Ellen DeGeneres",
"La inspiración existe, no obstante, hay que encontrarla trabajando. — Pablo Picasso",
"Cada segundo es tiempo de cambiar todo para siempre. — Charles Chaplin",
"No hay nada como volver a un lugar que no ha cambiado para saber cuánto has cambiado tú. — Nelson Mandela",
"La vitalidad se demuestra no solo con resistencia, también con la capacidad de empezar de nuevo. — F. Scott Fitzgerald",
"Comienza donde estás, usa lo que tienes y haz lo que puedas. — Arthur Ashe",
"Valentía es saber lo que no hay que temer. — Platón",
]; 